dependecies:
  # - <Organization>/<Repository>@<version>
  - smartcontractkit/chainlink-brownie-contracts@0.6.1

compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.6.1"

dotenv: .env

networks:
  sepolia:
    eth_usd_price_feed: "0x694AA1769357215DE4FAC081bf1f309aDC325306"
    verify: True
  development:
    verify: False

wallets:
  from_key: ${PRIVATE_KEY}
